#ifndef ADCIRC_HASHLIB_GLOBAL_H
#define ADCIRC_HASHLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBADCIRCHASH_LIBRARY)
#  define LIBADCIRCHASHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define LIBADCIRCHASHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADCIRC_HASHLIB_GLOBAL_H
