#ifndef ADCIRC_HASHLIB_GLOBAL_H
#define ADCIRC_HASHLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ADCIRC_HASHLIB_LIBRARY)
#  define ADCIRC_HASHLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define ADCIRC_HASHLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // ADCIRC_HASHLIB_GLOBAL_H
